---
all:

  # hosts and hostvars and all shared vars
  hosts:
  
    aio:
      ansible_host: "{{ lookup('ansible.builtin.pipe', 'hostname -I | cut -d \" \" -f 1') }}"
      inventory_index: 1
      ansible_connection: local

  # groups and group vars
  children:
    deployment_controller:
      hosts:
        aio:
    deployment_nodes:
      hosts:
        aio:
